version: '3.8'
services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: lucid
            POSTGRES_USER: lucid
            POSTGRES_PASSWORD: lucid
        ports:
            - 5432:5432
